export const ExpAir = {
  en: `The ExpAIR project is a citizen science initiative on air quality in Brussels launched by BRAL in collaboration with Brussels Environment. This initiative measured NO₂ concentration in Brussels' outdoor air in 2023, notably through the establishment of a secondary network of 24 measuring points located in the most polluted areas of the region. These sites, mainly concentrated in the city center where pollution is higher according to CurieuzenAir results, were monitored for a year with results communicated every two weeks. The project invited citizens, organizations, and merchants to become sponsors of these measuring points to share the results with their networks.`,
  fr: `Le projet ExpAIR est une recherche citoyenne sur la qualité de l'air à Bruxelles lancée par le BRAL en collaboration avec Bruxelles Environnement. Cette initiative a mesuré la concentration de NO2 dans l'air extérieur bruxellois en 2023, notamment par la mise en place d'un réseau secondaire de 24 points de mesure situés dans les zones les plus polluées de la région. Ces sites, principalement concentrés dans le centre-ville où la pollution est plus élevée selon les résultats de CurieuzenAir, ont fait l'objet de mesures pendant un an avec des résultats communiqués tous les quinze jours. Le projet a invité les citoyens, organisations et commerçants à devenir parrains ou marraines de ces points de mesure afin de communiquer les résultats à leurs réseaux.`,
  nl: `Het ExpAIR-project is een burgerwetenschapsinitiatief over luchtkwaliteit in Brussel, gelanceerd door BRAL in samenwerking met Leefmilieu Brussel. Dit initiatief heeft in 2023 de NO₂-concentratie in de buitenlucht van Brussel gemeten, met name door de oprichting van een secundair netwerk van 24 meetpunten in de meest vervuilde gebieden van de regio. Deze locaties, voornamelijk geconcentreerd in het stadscentrum waar de vervuiling hoger is volgens de resultaten van CurieuzenAir, werden een jaar lang gemonitord met resultaten die om de twee weken werden gecommuniceerd. Het project nodigde burgers, organisaties en handelaars uit om peter of meter te worden van deze meetpunten om de resultaten te delen met hun netwerken.`,
}

export const CurieuzenAir = {
  en: `CurieuzenAir is a citizen science project that analyzed air quality in Brussels by mobilizing 3,000 citizens from September 25 to October 23, 2021. Organized by the University of Antwerp, BRAL and ULB, in collaboration with several partners, it measured NO₂ concentration in streets using sensors placed on facades. This initiative resulted in a detailed map of traffic impact on air pollution, revealing strong disparities between vulnerable neighborhoods and greener, more affluent areas. However, the results also show a clear improvement in Brussels' air quality in recent years.`,
  fr: `CurieuzenAir est un projet de science participative qui a analysé la qualité de l’air à Bruxelles en mobilisant 3 000 citoyens du 25 septembre au 23 octobre 2021. Organisé par l'Université d’Anvers, le BRAL et l’ULB, en collaboration avec plusieurs partenaires, il a permis de mesurer la concentration de NO₂ dans les rues grâce à des capteurs placés sur les façades. Cette initiative a abouti à une carte détaillée de l’impact du trafic sur la pollution de l’air, révélant de fortes disparités entre quartiers vulnérables et zones plus vertes et aisées. Toutefois, les résultats montrent aussi une nette amélioration de la qualité de l’air à Bruxelles ces dernières années.`,
  nl: `CurieuzenAir is een burgerwetenschap project dat de luchtkwaliteit in Brussel heeft geanalyseerd door 3.000 burgers te mobiliseren van 25 september tot 23 oktober 2021. Georganiseerd door de Universiteit Antwerpen, BRAL en de ULB, in samenwerking met verschillende partners, heeft het de NO₂-concentratie in straten gemeten met behulp van sensoren geplaatst op gevels. Dit initiatief resulteerde in een gedetailleerde kaart van de impact van verkeer op luchtvervuiling, waarbij sterke verschillen tussen kwetsbare wijken en groenere, welvarende gebieden aan het licht kwamen. De resultaten tonen echter ook een duidelijke verbetering van de luchtkwaliteit in Brussel in de afgelopen jaren.`,
}

export const luchtpijp = {
  en: `Luchtpijp is a Brussels-based citizen science project by beweging.net and the Christian Mutual Health Insurance that distributed 500 fine particle sensors to residents, with about 300 connected to a real-time map measuring PM10 and PM2.5 air pollution. The initiative aims to analyze neighborhood air quality differences to provide data-driven insights about air quality across different areas of the city. You can buy your own sensor and connection it to the network by visiting : https://sensor.community/`,
  fr: `Luchtpijp est un projet de science citoyenne bruxellois initié par beweging.net et la Mutualité Chrétienne qui a distribué 500 capteurs de particules fines aux résidents, dont environ 300 sont connectés à une carte en temps réel mesurant la pollution atmosphérique PM10 et PM2,5. L'initiative vise à analyser les différences de qualité de l'air entre les quartiers afin de fournir des informations basées sur des données concernant la qualité de l'air dans différentes zones de la ville. Vous pouvez acheter votre propre capteur et le connecter au réseau en visitant : https://sensor.community/`,
  nl: `Luchtpijp is een Brussels burgerwetenschapsproject van beweging.net en de Christelijke Mutualiteit dat 500 fijnstof-sensoren heeft verdeeld onder inwoners, waarvan er ongeveer 300 zijn aangesloten op een realtime kaart die PM10- en PM2,5-luchtvervuiling meet. Het initiatief streeft ernaar verschillen in luchtkwaliteit tussen wijken te analyseren om op gegevens gebaseerde inzichten te verstrekken over de luchtkwaliteit in verschillende delen van de stad. Je kunt je eigen sensor kopen en deze aansluiten op het netwerk door een bezoek te brengen aan: https://sensor.community/`,
}

export const pm2Info = {
  en: `PM2.5 refers to fine particulate matter with a diameter of 2.5 micrometers or smaller. These tiny particles can penetrate deep into the lungs and even enter the bloodstream, causing respiratory and cardiovascular diseases, worsening asthma, and increasing the risk of premature death.
      The main sources of PM2.5 pollution include vehicle emissions, industrial processes, wood burning, and other combustion activities. Urban areas with heavy traffic and industrial activity tend to have higher concentrations of PM2.5.`,
  fr: `PM2.5 désigne les particules fines dont le diamètre est inférieur ou égal à 2,5 micromètres. Ces particules peuvent pénétrer profondément dans les poumons et même atteindre la circulation sanguine, provoquant des maladies respiratoires et cardiovasculaires, aggravant l'asthme et augmentant le risque de décès prématuré.
      Les principales sources de pollution par les PM2.5 sont les émissions des véhicules, les processus industriels, la combustion du bois et d'autres activités de combustion. Les zones urbaines avec un trafic dense et une forte activité industrielle ont généralement des concentrations plus élevées de PM2.5.`,
  nl: `PM2.5 verwijst naar fijne deeltjes met een diameter van 2,5 micrometer of kleiner. Deze deeltjes kunnen diep in de longen doordringen en zelfs in de bloedbaan terechtkomen, wat kan leiden tot ademhalings- en hart- en vaatziekten, verergering van astma en een verhoogd risico op vroegtijdig overlijden.
        De belangrijkste bronnen van PM2.5-vervuiling zijn uitlaatgassen van voertuigen, industriële processen, houtverbranding en andere verbrandingsactiviteiten. Stedelijke gebieden met veel verkeer en industriële activiteit hebben doorgaans hogere concentraties PM2.5.`,
}

export const no2Info = {
  en: `NO₂ (nitrogen dioxide) is a harmful gas primarily produced by burning fossil fuels, especially from vehicle exhaust, industrial processes, and power plants.
      Exposure to NO₂ can cause respiratory problems, aggravate asthma, and increase the risk of lung infections. Long-term exposure is linked to reduced lung function and cardiovascular diseases.
      Urban areas with heavy traffic and industrial activity tend to have the highest NO₂ concentrations, making it a major air pollutant in cities.`,
  fr: `Le NO₂ (dioxyde d'azote) est un gaz nocif principalement produit par la combustion des énergies fossiles, notamment les gaz d’échappement des véhicules, les processus industriels et les centrales électriques.
      L'exposition au NO₂ peut provoquer des problèmes respiratoires, aggraver l'asthme et augmenter le risque d'infections pulmonaires. Une exposition prolongée est associée à une diminution de la fonction pulmonaire et à des maladies cardiovasculaires.
      Les zones urbaines avec un trafic dense et une forte activité industrielle présentent généralement les concentrations les plus élevées de NO₂, ce qui en fait un polluant majeur dans les villes.`,
  nl: `NO₂ (stikstofdioxide) is een schadelijk gas dat voornamelijk wordt geproduceerd door de verbranding van fossiele brandstoffen, vooral door uitlaatgassen van voertuigen, industriële processen en elektriciteitscentrales.
      Blootstelling aan NO₂ kan ademhalingsproblemen veroorzaken, astma verergeren en het risico op longinfecties verhogen. Langdurige blootstelling wordt in verband gebracht met een verminderde longfunctie en hart- en vaatziekten.
      Stedelijke gebieden met veel verkeer en industriële activiteit hebben doorgaans de hoogste NO₂-concentraties, waardoor het een belangrijke luchtvervuiler in steden is.`,
}

export const ircelineInfo = {
  en: `IRCEL - CELINE is the interregional environmental cell that provides information on ambient air quality in Belgium.`,
  fr: `IRCEL - CELINE est la cellule interrégionale de l'environnement informant sur la qualité de l'air ambiant en Belgique.`,
  nl: `IRCEL - CELINE is de interregionale milieucel die informatie verstrekt over de luchtkwaliteit in België.`,
}
